[package]
name = "proll"
version = "0.0.1"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.17", features = ["derive"] }
colored = "2.1.0"
minreq = {version = "2.12.0", features = ["https"] }
xz = "0.1.0"
